export const UNIVERSITY_REQUEST = "UNIVERSITY_REQUEST";
export const UNIVERSITY_ERROR = "UNIVERSITY_ERROR";

// Post

export const POST_UNIVERSITY_SUCCESS = "POST_UNIVERSITY_SUCCESS";

// Get

export const GET_UNIVERSITY_SUCCESS = "GET_UNIVERSITY_SUCCESS";

// Edit

export const EDIT_UNIVERSITY = "EDIT_UNIVERSITY";

// DELETE

export const DELETE_UNIVERSITY = "DELETE_UNIVERSITY"
